Repository CSCfi/metadata-submitter-frontend, pull requests merged in 2020-11, with the labels that each got.

#86 "Save and Exit"/"Publish" actions in wizard
  src/components/NewDraftWizard/WizardComponents/WizardAlert.js
  src/components/NewDraftWizard/WizardComponents/WizardFooter.js
  src/features/wizardSubmissionFolderSlice.js
Labels: enhancement

#89 Feature/folder form edit
  src/components/NewDraftWizard/WizardSteps/WizardCreateFolderStep.js
  src/features/wizardSubmissionFolderSlice.js
Labels: enhancement

#92 Feature/saved objects info
  src/__tests__/WizardSavedObjectsList.test.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectsList.js
  src/components/NewDraftWizard/WizardSteps/WizardAddObjectStep.js
  src/features/wizardSubmissionFolderSlice.js
  src/theme.js
Labels: enhancement

#95 Bugfix/prevent draft version alert popping incorrectly
  src/__tests__/WizardAddObjectStep.test.js
  src/__tests__/WizardStepper.test.js
  src/__tests__/WizardUploadObjectXMLForm.test.js
  src/components/NewDraftWizard/WizardComponents/WizardAddObjectCard.js
  src/components/NewDraftWizard/WizardComponents/WizardObjectIndex.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectsList.js
  src/components/NewDraftWizard/WizardComponents/WizardStepper.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/components/NewDraftWizard/WizardForms/WizardUploadObjectXMLForm.js
  src/features/draftStatusSlice.js
  src/rootReducer.js
Labels: bug, enhancement

#97 Feature/folder backend check
  src/components/NewDraftWizard/WizardComponents/WizardAlert.js
  src/components/NewDraftWizard/WizardComponents/WizardFooter.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectsList.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/components/NewDraftWizard/WizardSteps/WizardCreateFolderStep.js
  src/features/wizardSubmissionFolderSlice.js
Labels: enhancement

#99 Bugfix/keyboard based xml upload
  src/components/NewDraftWizard/WizardForms/WizardUploadObjectXMLForm.js
Labels: bug

#100 bump to version 0.5.0
  architecture.md
  enzyme.js
  package-lock.json
  package.json
  src/__tests__/Nav.test.js
  src/__tests__/WizardAddObjectStep.test.js
  src/__tests__/WizardAlert.test.js
  src/__tests__/WizardFillObjectDetailsForm.test.js
  src/__tests__/WizardFooter.test.js
  src/__tests__/WizardSavedObjectsList.test.js
  src/__tests__/WizardShowSummaryStep.test.js
  src/__tests__/WizardStatusMessageHandler.test.js
  src/__tests__/WizardStepper.test.js
  src/__tests__/WizardUploadObjectXMLForm.test.js
  src/__tests__/index.test.js
  src/components/NewDraftWizard/WizardComponents/WizardAddObjectCard.js
  src/components/NewDraftWizard/WizardComponents/WizardAlert.js
  src/components/NewDraftWizard/WizardComponents/WizardFooter.js
  src/components/NewDraftWizard/WizardComponents/WizardObjectIndex.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectsList.js
  src/components/NewDraftWizard/WizardComponents/WizardStepper.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/components/NewDraftWizard/WizardForms/WizardStatusMessageHandler.js
  src/components/NewDraftWizard/WizardForms/WizardStatusMessageHandler.test.js
  src/components/NewDraftWizard/WizardForms/WizardUploadObjectXMLForm.js
  src/components/NewDraftWizard/WizardSteps/WizardAddObjectStep.js
  src/components/NewDraftWizard/WizardSteps/WizardCreateFolderStep.js
  src/components/NewDraftWizard/WizardSteps/WizardShowSummaryStep.js
  src/features/draftStatusSlice.js
  src/features/wizardSubmissionFolderSlice.js
  src/rootReducer.js
  src/setupTests.js
  src/theme.js
  src/views/NewDraftWizard.js
Labels: release
