Repository CSCfi/metadata-submitter-frontend, pull requests merged in 2021-04, with the labels that each got.

#224 bump to 0.9.2
  README.md
  cypress/integration/app.spec.js
  cypress/integration/errorPages.spec.js
  cypress/integration/objectLinksAttributes.spec.js
  package-lock.json
  package.json
  src/__tests__/NewDraftWizard.test.js
  src/__tests__/WizardAddObjectStep.test.js
  src/__tests__/WizardFillObjectDetailsForm.test.js
  src/__tests__/WizardFooter.test.js
  src/__tests__/WizardShowSummaryStep.test.js
  src/__tests__/WizardStepper.test.js
  src/components/NewDraftWizard/WizardComponents/WizardFooter.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectActions.js
  src/components/NewDraftWizard/WizardComponents/WizardStepper.js
  src/components/NewDraftWizard/WizardForms/WizardAjvResolver.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/components/NewDraftWizard/WizardForms/WizardJSONSchemaParser.js
  src/components/NewDraftWizard/WizardSteps/WizardCreateFolderStep.js
  src/components/NewDraftWizard/WizardSteps/WizardFrontpageStep.js
  src/features/wizardStepSlice.js
  src/rootReducer.js
  src/utils/index.js
  src/views/NewDraftWizard.js
Labels: release

#234 Feature/draft selections
  cypress/integration/draftTemplates.spec.js
  cypress/integration/errorPages.spec.js
  src/components/NewDraftWizard/WizardComponents/WizardAlert.js
  src/components/NewDraftWizard/WizardComponents/WizardDraftSelections.js
  src/components/NewDraftWizard/WizardComponents/WizardFooter.js
  src/features/userSlice.js
  src/services/usersAPI.js
Labels: enhancement

#233 DAC is an acronym treat it as one
  src/components/NewDraftWizard/WizardComponents/WizardObjectIndex.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectsList.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/components/NewDraftWizard/WizardSteps/WizardShowSummaryStep.js
  src/utils/index.js
Labels: bug

#257 Feature/user draft templates
  cypress/integration/app.spec.js
  cypress/integration/draft.spec.js
  cypress/integration/draftTemplates.spec.js
  cypress/integration/emptyForm.spec.js
  cypress/integration/objectLinksAttributes.spec.js
  cypress/integration/objectTitles.spec.js
  src/components/Home/SubmissionIndexCard.js
  src/components/Home/UserDraftTemplates.js
  src/components/NewDraftWizard/WizardComponents/WizardDraftSelections.js
  src/components/NewDraftWizard/WizardComponents/WizardObjectIndex.js
  src/utils/index.js
  src/views/Home.js
Labels: enhancement

#258 Bugfix/wrong prefilled inputs in forms
  cypress/integration/emptyForm.spec.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
Labels: bug

#269 find xml upload input easier for testing
  src/__tests__/WizardUploadObjectXMLForm.test.js
  src/components/NewDraftWizard/WizardForms/WizardUploadObjectXMLForm.js
Labels: bug
