Repository CSCfi/metadata-submitter-frontend, pull requests merged in 2021-08, with the labels that each got.

#400 Folders and user draft templates pagination
  cypress/integration/draftTemplates.spec.js
  cypress/integration/errorPages.spec.js
  cypress/integration/home.spec.js
  cypress/integration/pagination.spec.js
  src/__tests__/PublishedFoldersList.test.js
  src/__tests__/UnpublishedFoldersList.test.js
  src/components/ErrorPageContainer.js
  src/components/Home/SelectedFolderDetails.js
  src/components/Home/SubmissionDetailTable.js
  src/components/Home/SubmissionFolderList.js
  src/components/Home/SubmissionIndexCard.js
  src/components/Home/UserDraftTemplates.js
  src/components/NewDraftWizard/WizardSteps/WizardFrontpageStep.js
  src/features/publishedFoldersSlice.js
  src/features/totalFoldersSlice.js
  src/features/unpublishedFoldersSlice.js
  src/features/userSlice.js
  src/rootReducer.js
  src/services/folderAPI.js
  src/theme.js
  src/utils/index.js
  src/views/Home.js
  src/views/Login.js
Labels: enhancement

#403 Fix for Null value of PrevStepIndex
  src/components/NewDraftWizard/WizardForms/WizardJSONSchemaParser.js
Labels: bug

#417 Fix for object before patching
  cypress/integration/editForm.spec.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/components/NewDraftWizard/WizardForms/WizardJSONSchemaParser.js
Labels: bug

#424 Fix for pagination's usability
  cypress/integration/pagination.spec.js
  src/__tests__/PublishedFoldersList.test.js
  src/__tests__/UnpublishedFoldersList.test.js
  src/utils/index.js
Labels: enhancement

#421 Feature/edit publish draft folder
  .gitignore
  cypress/integration/home.spec.js
  src/__tests__/SubmissionDetailTable.test.js
  src/components/Home/SelectedFolderDetails.js
  src/components/Home/SubmissionDetailTable.js
  src/components/Home/SubmissionIndexCard.js
  src/components/Nav.js
  src/components/NewDraftWizard/WizardForms/WizardJSONSchemaParser.js
  src/constants/wizardObject.js
  src/theme.js
  src/types/index.js
Labels: enhancement

#425 Feature/accessible drafts
  cypress/integration/draft.spec.js
  cypress/integration/editForm.spec.js
  cypress/integration/emptyForm.spec.js
  cypress/integration/objectTitles.spec.js
  cypress/support/commands.js
  src/__tests__/WizardDraftObjectPicker.test.js
  src/__tests__/WizardSavedObjectsList.test.js
  src/components/NewDraftWizard/WizardComponents/WizardAddObjectCard.js
  src/components/NewDraftWizard/WizardComponents/WizardDraftObjectPicker.js
  src/components/NewDraftWizard/WizardComponents/WizardObjectIndex.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectActions.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectsList.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/components/NewDraftWizard/WizardForms/WizardStatusMessageHandler.js
  src/components/NewDraftWizard/WizardForms/WizardUploadObjectXMLForm.js
  src/components/NewDraftWizard/WizardHooks/WizardSaveDraftHook.js
  src/components/NewDraftWizard/WizardHooks/WizardSubmitObjectHook.js
  src/components/NewDraftWizard/WizardSteps/WizardAddObjectStep.js
  src/components/NewDraftWizard/WizardSteps/WizardShowSummaryStep.js
  src/constants/wizardObject.js
  src/features/loadingSlice.js
  src/rootReducer.js
  src/theme.js
Labels: enhancement

#432 Release 0.11.0
  .github/workflows/codestyle.yml
  .github/workflows/e2etests.yml
  .github/workflows/formatstyle.yml
  .github/workflows/typecheck.yml
  .github/workflows/unittests.yml
  .gitignore
  cypress.json
  cypress/integration/draft.spec.js
  cypress/integration/editForm.spec.js
  cypress/integration/emptyForm.spec.js
  cypress/integration/home.spec.js
  cypress/integration/objectTitles.spec.js
  cypress/integration/pagination.spec.js
  cypress/support/commands.js
  package-lock.json
  package.json
  src/__tests__/FormAutocompleteField.test.js
  src/__tests__/PublishedFoldersList.test.js
  src/__tests__/SubmissionDetailTable.test.js
  src/__tests__/UnpublishedFoldersList.test.js
  src/__tests__/WizardDraftObjectPicker.test.js
  src/__tests__/WizardFillObjectDetailsForm.test.js
  src/__tests__/WizardSavedObjectsList.test.js
  src/components/Home/SelectedFolderDetails.js
  src/components/Home/SubmissionDetailTable.js
  src/components/Home/SubmissionIndexCard.js
  src/components/Nav.js
  src/components/NewDraftWizard/WizardComponents/WizardAddObjectCard.js
  src/components/NewDraftWizard/WizardComponents/WizardDraftObjectPicker.js
  src/components/NewDraftWizard/WizardComponents/WizardObjectIndex.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectActions.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectsList.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/components/NewDraftWizard/WizardForms/WizardJSONSchemaParser.js
  src/components/NewDraftWizard/WizardForms/WizardStatusMessageHandler.js
  src/components/NewDraftWizard/WizardForms/WizardUploadObjectXMLForm.js
  src/components/NewDraftWizard/WizardHooks/WizardSaveDraftHook.js
  src/components/NewDraftWizard/WizardHooks/WizardSubmitObjectHook.js
  src/components/NewDraftWizard/WizardSteps/WizardAddObjectStep.js
  src/components/NewDraftWizard/WizardSteps/WizardShowSummaryStep.js
  src/constants/wizardObject.js
  src/features/clearFormSlice.js
  src/features/loadingSlice.js
  src/rootReducer.js
  src/theme.js
  src/types/index.js
  src/utils/index.js
Labels: release
