Repository CSCfi/metadata-submitter-frontend, pull requests merged in 2021-02, with the labels that each got.

#146 Bugfix/clear form button
  cypress/integration/app.spec.js
  cypress/integration/draft.spec.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
Labels: bug

#149 Feature/option to create new form
  cypress/integration/app.spec.js
  cypress/integration/draft.spec.js
  src/components/NewDraftWizard/WizardComponents/WizardAddObjectCard.js
  src/components/NewDraftWizard/WizardComponents/WizardDraftObjectPicker.js
  src/components/NewDraftWizard/WizardComponents/WizardFooter.js
  src/components/NewDraftWizard/WizardComponents/WizardObjectIndex.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/components/NewDraftWizard/WizardForms/WizardUploadObjectXMLForm.js
Labels: enhancement

#152 Bugfix/too many api calls
  cypress/integration/home.spec.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/services/folderAPI.js
  src/views/Home.js
Labels: bug

#156 Fix for saving multiple drafts when clicking Next and Back
  src/components/NewDraftWizard/WizardSteps/WizardCreateFolderStep.js
  src/features/wizardSubmissionFolderSlice.js
Labels: bug

#161 Edit saved form & replace saved XML functionality
  cypress/fixtures/study_test_modified.xml
  cypress/integration/app.spec.js
  src/__tests__/WizardShowSummaryStep.test.js
  src/components/NewDraftWizard/WizardComponents/WizardAlert.js
  src/components/NewDraftWizard/WizardComponents/WizardDraftObjectPicker.js
  src/components/NewDraftWizard/WizardComponents/WizardObjectIndex.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectActions.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectsList.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/components/NewDraftWizard/WizardForms/WizardStatusMessageHandler.js
  src/components/NewDraftWizard/WizardForms/WizardUploadObjectXMLForm.js
  src/components/NewDraftWizard/WizardSteps/WizardShowSummaryStep.js
  src/features/wizardCurrentObjectSlice.js
  src/features/wizardDraftObjectSlice.js
  src/features/wizardSubmissionFolderSlice.js
  src/rootReducer.js
  src/services/objectAPI.js
Labels: enhancement

#165 bump to 0.8.0
  cypress/fixtures/study_test_modified.xml
  cypress/integration/app.spec.js
  cypress/integration/draft.spec.js
  cypress/integration/emptyForm.spec.js
  cypress/integration/home.spec.js
  package-lock.json
  package.json
  src/__tests__/Home.test.js
  src/__tests__/Page403.test.js
  src/__tests__/WizardFooter.test.js
  src/__tests__/WizardSavedObjectsList.test.js
  src/__tests__/WizardShowSummaryStep.test.js
  src/components/Home/SubmissionDetailTable.js
  src/components/Home/SubmissionIndexCard.js
  src/components/NewDraftWizard/WizardComponents/WizardAddObjectCard.js
  src/components/NewDraftWizard/WizardComponents/WizardAlert.js
  src/components/NewDraftWizard/WizardComponents/WizardDraftObjectPicker.js
  src/components/NewDraftWizard/WizardComponents/WizardFooter.js
  src/components/NewDraftWizard/WizardComponents/WizardObjectIndex.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectActions.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectsList.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/components/NewDraftWizard/WizardForms/WizardStatusMessageHandler.js
  src/components/NewDraftWizard/WizardForms/WizardUploadObjectXMLForm.js
  src/components/NewDraftWizard/WizardSteps/WizardAddObjectStep.js
  src/components/NewDraftWizard/WizardSteps/WizardCreateFolderStep.js
  src/components/NewDraftWizard/WizardSteps/WizardShowSummaryStep.js
  src/features/focusSlice.js
  src/features/publishedFoldersSlice.js
  src/features/selectedFolderSlice.js
  src/features/unpublishedFoldersSlice.js
  src/features/wizardCurrentObjectSlice.js
  src/features/wizardDraftObjectSlice.js
  src/features/wizardSubmissionFolderSlice.js
  src/rootReducer.js
  src/services/folderAPI.js
  src/services/objectAPI.js
  src/services/usersAPI.js
  src/views/Home.js
Labels: release

#168 Feature/constant files
  .husky/.gitignore
  .husky/pre-commit
  cypress/integration/app.spec.js
  cypress/integration/draft.spec.js
  package-lock.json
  package.json
  src/__tests__/WizardAddObjectStep.test.js
  src/__tests__/WizardAlert.test.js
  src/__tests__/WizardDraftObjectPicker.test.js
  src/__tests__/WizardFillObjectDetailsForm.test.js
  src/__tests__/WizardFooter.test.js
  src/__tests__/WizardObjectIndex.test.js
  src/__tests__/WizardSavedObjectsList.test.js
  src/__tests__/WizardShowSummaryStep.test.js
  src/__tests__/WizardStatusMessageHandler.test.js
  src/__tests__/WizardStepper.test.js
  src/__tests__/WizardUploadObjectXMLForm.test.js
  src/components/Home/SubmissionDetailTable.js
  src/components/Home/SubmissionIndexCard.js
  src/components/NewDraftWizard/WizardComponents/WizardAddObjectCard.js
  src/components/NewDraftWizard/WizardComponents/WizardAlert.js
  src/components/NewDraftWizard/WizardComponents/WizardDraftObjectPicker.js
  src/components/NewDraftWizard/WizardComponents/WizardFooter.js
  src/components/NewDraftWizard/WizardComponents/WizardObjectIndex.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectActions.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectsList.js
  src/components/NewDraftWizard/WizardForms/WizardAjvResolver.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/components/NewDraftWizard/WizardForms/WizardStatusMessageHandler.js
  src/components/NewDraftWizard/WizardForms/WizardUploadObjectXMLForm.js
  src/components/NewDraftWizard/WizardSteps/WizardCreateFolderStep.js
  src/components/NewDraftWizard/WizardSteps/WizardShowSummaryStep.js
  src/constants/folder.js
  src/constants/object.js
  src/constants/wizardStatus.js
  src/features/selectedFolderSlice.js
  src/features/unpublishedFoldersSlice.js
  src/features/wizardSubmissionFolderSlice.js
  src/views/Home.js
Labels: documentation, enhancement
