Repository CSCfi/metadata-submitter-frontend, pull requests merged in 2021-03, with the labels that each got.

#171 Feature/update flow and data types
  package-lock.json
  package.json
  src/App.js
  src/components/ErrorPageContainer.js
  src/components/Home/SubmissionDetailTable.js
  src/components/Home/SubmissionIndexCard.js
  src/components/Nav.js
  src/components/NewDraftWizard/WizardComponents/WizardAddObjectCard.js
  src/components/NewDraftWizard/WizardComponents/WizardAlert.js
  src/components/NewDraftWizard/WizardComponents/WizardDraftObjectPicker.js
  src/components/NewDraftWizard/WizardComponents/WizardFooter.js
  src/components/NewDraftWizard/WizardComponents/WizardHeader.js
  src/components/NewDraftWizard/WizardComponents/WizardObjectIndex.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectActions.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectsList.js
  src/components/NewDraftWizard/WizardComponents/WizardStepper.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/components/NewDraftWizard/WizardForms/WizardJSONSchemaParser.js
  src/components/NewDraftWizard/WizardForms/WizardStatusMessageHandler.js
  src/components/NewDraftWizard/WizardForms/WizardUploadObjectXMLForm.js
  src/components/NewDraftWizard/WizardSteps/WizardAddObjectStep.js
  src/components/NewDraftWizard/WizardSteps/WizardCreateFolderStep.js
  src/components/NewDraftWizard/WizardSteps/WizardFrontpageStep.js
  src/components/NewDraftWizard/WizardSteps/WizardShowSummaryStep.js
  src/features/draftStatusSlice.js
  src/features/focusSlice.js
  src/features/publishedFoldersSlice.js
  src/features/selectedFolderSlice.js
  src/features/unpublishedFoldersSlice.js
  src/features/userSlice.js
  src/features/wizardAlertSlice.js
  src/features/wizardCurrentObjectSlice.js
  src/features/wizardObjectTypeSlice.js
  src/features/wizardStatusMessageSlice.js
  src/features/wizardStepSlice.js
  src/features/wizardSubmissionFolderSlice.js
  src/features/wizardSubmissionTypeSlice.js
  src/rootReducer.js
  src/services/draftAPI.js
  src/services/folderAPI.js
  src/services/objectAPI.js
  src/services/publishAPI.js
  src/services/schemaAPI.js
  src/services/submissionAPI.js
  src/services/usersAPI.js
  src/store.js
  src/types/index.js
  src/views/ErrorPages/ErrorPagesHelper.js
  src/views/ErrorPages/Page401.js
  src/views/ErrorPages/Page403.js
  src/views/ErrorPages/Page404.js
  src/views/ErrorPages/Page500.js
  src/views/Home.js
  src/views/Login.js
  src/views/NewDraftWizard.js
Labels: documentation, enhancement

#178 Bugfix/form renders multiple times
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
Labels: bug

#180 Docs/predefined values and data types
  architecture.md
  src/__tests__/WizardAddObjectStep.test.js
  src/__tests__/WizardAlert.test.js
  src/__tests__/WizardDraftObjectPicker.test.js
  src/__tests__/WizardFillObjectDetailsForm.test.js
  src/__tests__/WizardFooter.test.js
  src/__tests__/WizardObjectIndex.test.js
  src/__tests__/WizardSavedObjectsList.test.js
  src/__tests__/WizardShowSummaryStep.test.js
  src/__tests__/WizardStepper.test.js
  src/__tests__/WizardUploadObjectXMLForm.test.js
  src/components/Home/SubmissionDetailTable.js
  src/components/Home/SubmissionIndexCard.js
  src/components/NewDraftWizard/WizardComponents/WizardAddObjectCard.js
  src/components/NewDraftWizard/WizardComponents/WizardAlert.js
  src/components/NewDraftWizard/WizardComponents/WizardDraftObjectPicker.js
  src/components/NewDraftWizard/WizardComponents/WizardObjectIndex.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectActions.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectsList.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/components/NewDraftWizard/WizardForms/WizardUploadObjectXMLForm.js
  src/components/NewDraftWizard/WizardSteps/WizardShowSummaryStep.js
  src/constants/wizardFolder.js
  src/constants/wizardObject.js
  src/features/objectsArraySlice.js
  src/features/selectedFolderSlice.js
  src/features/unpublishedFoldersSlice.js
  src/features/wizardSubmissionFolderSlice.js
  src/rootReducer.js
  src/services/schemaAPI.js
  src/views/Home.js
Labels: documentation

#185 Custom hook for draft saving
  cypress/integration/draft.spec.js
  src/components/NewDraftWizard/WizardComponents/WizardAlert.js
  src/components/NewDraftWizard/WizardComponents/WizardDraftObjectPicker.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectActions.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/components/NewDraftWizard/WizardForms/WizardUploadObjectXMLForm.js
  src/components/NewDraftWizard/WizardHooks/WizardSaveDraftHook.js
Labels: enhancement

#187 Feature/display object titles
  cypress/integration/objectTitles.spec.js
  src/__tests__/WizardDraftObjectPicker.test.js
  src/__tests__/WizardSavedObjectsList.test.js
  src/__tests__/WizardShowSummaryStep.test.js
  src/components/NewDraftWizard/WizardComponents/WizardDraftObjectPicker.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectsList.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/components/NewDraftWizard/WizardHooks/WizardSaveDraftHook.js
  src/components/NewDraftWizard/WizardSteps/WizardShowSummaryStep.js
  src/features/wizardSubmissionFolderSlice.js
  src/types/index.js
  src/utils/index.js
Labels: enhancement

#188 add custom ajv JSON schema formats
  package-lock.json
  package.json
  src/components/NewDraftWizard/WizardForms/WizardAjvResolver.js
Labels: bug

#202 bump 0.9.1
  .github/dependabot.yml
  .github/workflows/codestyle.yml
  .github/workflows/formatstyle.yml
  .github/workflows/typecheck.yml
  .github/workflows/unittests.yml
  package-lock.json
  package.json
Labels: github actions, npm dependencies

#205 Bugfix/links and attributes
  cypress/integration/app.spec.js
  cypress/integration/objectLinksAttributes.spec.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectActions.js
  src/components/NewDraftWizard/WizardForms/WizardJSONSchemaParser.js
Labels: bug

#219 move ajv to v8+ dataPath -> instancePath
  src/components/NewDraftWizard/WizardForms/WizardAjvResolver.js
Labels: bug

#222 Test blur on form field
  src/__tests__/WizardFillObjectDetailsForm.test.js
  src/components/NewDraftWizard/WizardForms/WizardAjvResolver.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/components/NewDraftWizard/WizardForms/WizardJSONSchemaParser.js
Labels: enhancement

#223 Tests for error pages
  cypress/integration/errorPages.spec.js
Labels: enhancement
