Repository CSCfi/metadata-submitter-frontend, pull requests merged in 2021-01, with the labels that each got.

#124 change from getuserid to getUserById
  src/features/userSlice.js
  src/services/usersAPI.js
Labels: bug

#130 Hotfix/apisauce update
  package-lock.json
  package.json
Labels: bug

#134 bump to 0.7.0
  .gitignore
  cypress/integration/app.spec.js
  cypress/integration/draft.spec.js
  package-lock.json
  package.json
  src/__tests__/WizardDraftObjectPicker.test.js
  src/__tests__/WizardFillObjectDetailsForm.test.js
  src/__tests__/WizardObjectIndex.test.js
  src/__tests__/WizardSavedObjectsList.test.js
  src/components/NewDraftWizard/WizardComponents/WizardAddObjectCard.js
  src/components/NewDraftWizard/WizardComponents/WizardAlert.js
  src/components/NewDraftWizard/WizardComponents/WizardDraftObjectPicker.js
  src/components/NewDraftWizard/WizardComponents/WizardObjectIndex.js
  src/components/NewDraftWizard/WizardComponents/WizardSavedObjectsList.js
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.js
  src/components/NewDraftWizard/WizardSteps/WizardCreateFolderStep.js
  src/features/wizardSubmissionFolderSlice.js
  src/services/draftAPI.js
  src/setupTests.js
Labels: release

#136 Feature/drafts and folders in homepage
  cypress/integration/home.spec.js
  src/__tests__/Home.test.js
  src/__tests__/Page403.test.js
  src/components/Home/SubmissionDetailTable.js
  src/components/Home/SubmissionIndexCard.js
  src/components/NewDraftWizard/WizardComponents/WizardObjectIndex.js
  src/features/publishedFoldersSlice.js
  src/features/selectedFolderSlice.js
  src/features/unpublishedFoldersSlice.js
  src/rootReducer.js
  src/services/usersAPI.js
  src/views/Home.js
Labels: enhancement

#140 Bugfix/restrict empty folder publish
  src/__tests__/WizardFooter.test.js
  src/components/NewDraftWizard/WizardComponents/WizardFooter.js
Labels: bug
