Repository CSCfi/metadata-submitter-frontend, pull requests merged in 2022-05, with the labels that each got.

#792 Catch the error for not filling Keywords in DOI form
  src/components/SubmissionWizard/WizardForms/WizardJSONSchemaParser.tsx
Labels: bug

#763 Feature/stepper accordion
  CHANGELOG.md
  cypress/fixtures/test-objects.ts
  cypress/integration/app.spec.ts
  cypress/integration/doiForm.spec.ts
  cypress/integration/draft.spec.ts
  cypress/integration/draftTemplates.spec.ts
  cypress/integration/editForm.spec.ts
  cypress/integration/emptyForm.spec.ts
  cypress/integration/fieldValidation.spec.ts
  cypress/integration/generateObjects.spec.ts
  cypress/integration/home.spec.ts
  cypress/integration/linkingAccessionIds.spec.ts
  cypress/integration/objectLinksAttributes.spec.ts
  cypress/integration/objectTitles.spec.ts
  cypress/support/commands.ts
  package-lock.json
  src/App.tsx
  src/__tests__/SubmissionWizard.test.tsx
  src/__tests__/WizardStepper.test.tsx
  src/components/Home/SubmissionDataTable.tsx
  src/components/Nav.tsx
  src/components/SubmissionWizard/WizardComponents/WizardAddObjectCard.tsx
  src/components/SubmissionWizard/WizardComponents/WizardAlert.tsx
  src/components/SubmissionWizard/WizardComponents/WizardDraftSelections.tsx
  src/components/SubmissionWizard/WizardComponents/WizardStep.tsx
  src/components/SubmissionWizard/WizardComponents/WizardStepper.tsx
  src/components/SubmissionWizard/WizardForms/WizardFillObjectDetailsForm.tsx
  src/components/SubmissionWizard/WizardSteps/WizardAddObjectStep.tsx
  src/components/SubmissionWizard/WizardSteps/WizardCreateFolderStep.tsx
  src/components/SubmissionWizard/WizardSteps/WizardShowSummaryStep.tsx
  src/constants/wizardObject.ts
  src/features/wizardStepObjectSlice.tsx
  src/rootReducer.ts
  src/theme.ts
  src/types/index.ts
  src/types/theme.d.ts
  src/views/Home.tsx
  src/views/Submission.tsx
Labels: enhancement

#813 Change http --> https
  CHANGELOG.md
  src/__tests__/FormAutocompleteField.test.tsx
  src/services/rorAPI.ts
Labels: bug, frontend

#800 Feature/summary page
  CHANGELOG.md
  cypress/integration/app.spec.ts
  cypress/integration/draft.spec.ts
  cypress/integration/draftTemplates.spec.ts
  cypress/integration/generateObjects.spec.ts
  cypress/integration/home.spec.ts
  cypress/support/commands.ts
  src/__tests__/WizardShowSummaryStep.test.tsx
  src/components/SubmissionWizard/WizardComponents/WizardObjectStatusBadge.tsx
  src/components/SubmissionWizard/WizardComponents/WizardStep.tsx
  src/components/SubmissionWizard/WizardComponents/WizardStepper.tsx
  src/components/SubmissionWizard/WizardHooks/WizardEditObjectHook.tsx
  src/components/SubmissionWizard/WizardHooks/WizardMapObjectsToStepsHook.tsx
  src/components/SubmissionWizard/WizardSteps/WizardShowSummaryStep.tsx
  src/theme.ts
  src/types/index.ts
Labels: enhancement

#811 Feature/form and xml changes
  CHANGELOG.md
  cypress/integration/app.spec.ts
  cypress/integration/doiForm.spec.ts
  cypress/integration/draft.spec.ts
  cypress/integration/draftTemplates.spec.ts
  cypress/integration/editForm.spec.ts
  cypress/integration/emptyForm.spec.ts
  cypress/integration/home.spec.ts
  cypress/integration/objectLinksAttributes.spec.ts
  cypress/integration/objectTitles.spec.ts
  cypress/support/commands.ts
  src/__tests__/FormAutocompleteField.test.tsx
  src/__tests__/WizardAddObjectStep.test.tsx
  src/__tests__/WizardFillObjectDetailsForm.test.tsx
  src/__tests__/WizardJSONSchemaParser.test.tsx
  src/__tests__/WizardShowSummaryStep.test.tsx
  src/components/ErrorPageContainer.tsx
  src/components/Home/UserDraftTemplateActions.tsx
  src/components/SubmissionWizard/WizardComponents/WizardAddObjectCard.tsx
  src/components/SubmissionWizard/WizardComponents/WizardSavedObjectsList.tsx
  src/components/SubmissionWizard/WizardComponents/WizardStep.tsx
  src/components/SubmissionWizard/WizardComponents/WizardStepContentHeader.tsx
  src/components/SubmissionWizard/WizardComponents/WizardStepper.tsx
  src/components/SubmissionWizard/WizardForms/WizardDOIForm.tsx
  src/components/SubmissionWizard/WizardForms/WizardFillObjectDetailsForm.tsx
  src/components/SubmissionWizard/WizardForms/WizardJSONSchemaParser.tsx
  src/components/SubmissionWizard/WizardForms/WizardOptions.tsx
  src/components/SubmissionWizard/WizardForms/WizardUploadObjectXMLForm.tsx
  src/components/SubmissionWizard/WizardForms/WizardUploadXMLModal.tsx
  src/components/SubmissionWizard/WizardForms/WizardXMLObjectPage.tsx
  src/components/SubmissionWizard/WizardHooks/WizardSaveDraftHook.tsx
  src/components/SubmissionWizard/WizardSteps/WizardAddObjectStep.tsx
  src/components/SubmissionWizard/WizardSteps/WizardCreateSubmissionStep.tsx
  src/features/wizardCurrentObjectSlice.tsx
  src/features/wizardSubmissionSlice.tsx
  src/features/wizardXMLModalSlice.tsx
  src/rootReducer.ts
  src/services/errorMonitor.ts
  src/theme.ts
  src/types/index.ts
  src/types/theme.d.ts
  src/utils/index.tsx
  src/views/Submission.tsx
Labels: enhancement, new frontend
