Repository CSCfi/metadata-submitter-frontend, pull requests merged in 2022-03, with the labels that each got.

#674 Enable removal of field array items
  CHANGELOG.md
  cypress/integration/objectLinksAttributes.spec.ts
  package-lock.json
  src/components/NewDraftWizard/WizardForms/WizardJSONSchemaParser.tsx
Labels: bug

#685 Feature/filter functionality
  CHANGELOG.md
  cypress/integration/home.spec.ts
  cypress/integration/pagination.spec.ts
  src/__tests__/Home.test.tsx
  src/components/Home/SubmissionDataTable.tsx
  src/components/NewDraftWizard/WizardComponents/WizardPagination.tsx
  src/components/NewDraftWizard/WizardComponents/WizardSearchBox.tsx
  src/features/publishedFoldersSlice.tsx
  src/features/unpublishedFoldersSlice.tsx
  src/rootReducer.ts
  src/types/index.ts
  src/views/Home.tsx
Labels: enhancement

#696 Feature/project-id
  .github/workflows/e2etests.yml
  CHANGELOG.md
  cypress/integration/doiForm.spec.ts
  cypress/integration/home.spec.ts
  cypress/integration/objectLinksAttributes.spec.ts
  cypress/integration/pagination.spec.ts
  cypress/support/commands.ts
  src/__tests__/Home.test.tsx
  src/__tests__/Page403.test.tsx
  src/components/Home/SubmissionDataTable.tsx
  src/components/Home/UserDraftTemplateActions.tsx
  src/components/Home/UserDraftTemplates.tsx
  src/components/NewDraftWizard/WizardComponents/WizardFooter.tsx
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.tsx
  src/components/NewDraftWizard/WizardHooks/WizardSaveTemplatesHook.tsx
  src/components/NewDraftWizard/WizardSteps/WizardCreateFolderStep.tsx
  src/features/projectIdSlice.tsx
  src/features/templateAccessionIdsSlice.tsx
  src/features/templateSlice.tsx
  src/features/userSlice.tsx
  src/features/wizardSubmissionFolderSlice.tsx
  src/rootReducer.ts
  src/services/folderAPI.ts
  src/services/templateAPI.ts
  src/theme.ts
  src/types/index.ts
  src/views/Home.tsx
Labels: enhancement

#728 Target backend develop branch in E2E workflow
  .github/workflows/e2etests.yml
Labels: enhancement, github actions
