Repository CSCfi/metadata-submitter-frontend, pull requests merged in 2022-02, with the labels that each got.

#653 Feature/drag and drop file upload
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/NewDraftWizard/WizardForms/WizardUploadObjectXMLForm.tsx
Labels: enhancement

#655 Feature/workflows node js update
  .github/workflows/codestyle.yml
  .github/workflows/e2etests.yml
  .github/workflows/formatstyle.yml
  .github/workflows/typecheck.yml
  .github/workflows/unittests.yml
  CHANGELOG.md
  Dockerfile-dev
  README.md
Labels: enhancement

#656 Bugfix/disable invalid submitted object patch
  CHANGELOG.md
  cypress/integration/app.spec.ts
  cypress/integration/draftTemplates.spec.ts
  cypress/integration/editForm.spec.ts
  cypress/integration/home.spec.ts
  cypress/integration/objectTitles.spec.ts
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.tsx
Labels: bug

#661 Bugfix/invalid field format
  CHANGELOG.md
  src/components/NewDraftWizard/WizardForms/WizardJSONSchemaParser.tsx
Labels: bug

#666 Update text field value with setValue method
  CHANGELOG.md
  cypress/integration/app.spec.ts
  src/components/Home/UserDraftTemplates.tsx
  src/components/NewDraftWizard/WizardForms/WizardJSONSchemaParser.tsx
Labels: bug

#672 Bugfix/update Post and Patch objects and draft objects
  CHANGELOG.md
  architecture.md
  src/components/NewDraftWizard/WizardForms/WizardFillObjectDetailsForm.tsx
  src/components/NewDraftWizard/WizardForms/WizardUploadObjectXMLForm.tsx
  src/components/NewDraftWizard/WizardHooks/WizardSaveDraftHook.tsx
  src/components/NewDraftWizard/WizardHooks/WizardSubmitObjectHook.tsx
  src/components/NewDraftWizard/WizardHooks/WizardTransformTemplatesToDrafts.tsx
  src/components/NewDraftWizard/WizardSteps/WizardCreateFolderStep.tsx
  src/features/wizardSubmissionFolderSlice.tsx
  src/services/draftAPI.ts
  src/services/objectAPI.ts
Labels: bug, enhancement, frontend
